name: Automatic Rebase

on: [pull_request_target]

jobs:
  _:
    permissions:
      contents: write
    name: "Automatic Rebase"

    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@v1
      with:
        allowed-endpoints:
          api.github.com:443
          github.com:443
    - uses: actions/checkout@v2
    - uses: ljharb/rebase@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
